# -*- coding: utf-8 -*-
"""Performance of Pseudo and Random model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wjE7HiROm8KFeRIYj8q30Wynctlqqhr0

## Performance of Pseudo model
"""

import numpy as np
from sklearn import metrics
import random
y=[1 for i in range(0,10031)]
for i in range(10031):
  y.append(0)

y_true=np.array(y)
print(y)


y_=[1 for i in range(15031)]
for i in range(5031):
  y_.append(0)

y_pred=np.array(y_)
print(y_)



tpr, fpr, t= metrics.roc_curve(y_true, y_pred)
print("AUC of Pseudo model: ", metrics.auc(tpr, fpr))  
print("AUPRC of Pseudo model: ", metrics.average_precision_score(y_true, y_pred))

##Output
## AUC of Pseudo model:  0.7507726049247333
## AUPRC of Pseudo model:  0.6673541347881046

"""## Performance of Random model"""

import numpy as np
from sklearn import metrics
import random
y=[1 for i in range(0,10031)]
for i in range(10031):
  y.append(0)

y_true=np.array(y)
print(y)

y_=[]
for i in range(20062):
  y_.append(random.random())

y_pred=np.array(y_)
print(y_)



tpr, fpr, t= metrics.roc_curve(y_true, y_pred)
print("AUC of Pseudo model: ", metrics.auc(tpr, fpr))  
print("AUPRC of Pseudo model: ", metrics.average_precision_score(y_true, y_pred))

##Output
##AUC of Pseudo model:  0.49729377957342313
##AUPRC of Pseudo model:  0.4963834339283799